### PR TITLE
Escape special characters in SWC audio filenames

### PR DESCRIPTION
**Pull request by akreal**

### CODE REVIEW

**Comment by akoehn** [comment]
Sorry for the late reply, but why do these need replacement? A one-liner explaining the reason for that commit would be nice.

**Comment by akreal** [comment]
Here is a command to reproduce the problem (it works after the replacement):

```
$ echo "0000009_0000056 sox data/wav/swc/german/Neaira_(Het%c3%a4re)/audio.ogg --bits 16 --endian little --channels 1 --encoding signed-integer --rate 16000 -t wav - |" | compute-fbank-feats scp:- ark:/dev/null
compute-fbank-feats scp:- ark:/dev/null
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `sox data/wav/swc/german/Neaira_(Het%c3%a4re)/audio.ogg --bits 16 --endian little --channels 1 --encoding signed-integer --rate 16000 -t wav - '
ERROR (compute-fbank-feats[5.4.229~2-68c9]:Read4ByteTag():wave-reader.cc:56) WaveData: expected 4-byte chunk-name, got read error

[ Stack-Trace: ]
kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::WaveInfo::Read(std::istream&)
kaldi::WaveData::Read(std::istream&)
kaldi::SequentialTableReaderScriptImpl<kaldi::WaveHolder>::EnsureObjectLoaded()
kaldi::SequentialTableReaderScriptImpl<kaldi::WaveHolder>::Value()
main
__libc_start_main
_start

WARNING (compute-fbank-feats[5.4.229~2-68c9]:Read():feat/wave-reader.h:197) Exception caught in WaveHolder::Read().
WARNING (compute-fbank-feats[5.4.229~2-68c9]:EnsureObjectLoaded():util/kaldi-table-inl.h:317) Failed to load object from 'sox data/wav/swc/german/Neaira_(Het%c3%a4re)/audio.ogg --bits 16 --endian little --channels 1 --encoding signed-integer --rate 16000 -t wav - |'
ERROR (compute-fbank-feats[5.4.229~2-68c9]:Value():util/kaldi-table-inl.h:164) Failed to load object from 'sox data/wav/swc/german/Neaira_(Het%c3%a4re)/audio.ogg --bits 16 --endian little --channels 1 --encoding signed-integer --rate 16000 -t wav - |' (to suppress this error, add the permissive (p, ) option to the rspecifier.

[ Stack-Trace: ]
kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::SequentialTableReaderScriptImpl<kaldi::WaveHolder>::Value()
main
__libc_start_main
_start

WARNING (compute-fbank-feats[5.4.229~2-68c9]:Close():kaldi-io.cc:515) Pipe sox data/wav/swc/german/Neaira_(Het%c3%a4re)/audio.ogg --bits 16 --endian little --channels 1 --encoding signed-integer --rate 16000 -t wav - | had nonzero return status 256
```

Or did you mean I should include an explanation to the commit message?

**Comment by akoehn** [comment]
I figured it would be for shell escapes somehow but didn't know where. Is the data from wav.scp always piped into a shell? Because if it is not, this change might break other processors.

I don't really know about the processing part but my gut feeling would be to have the correct file name in the wav.scp and fix the processors to perform proper shell escapes when dealing with file names.

@bmilde, any comments?

**Comment by akreal** [comment]
The thing is that wav.scp may contain file names or shell commands (providing wav data on stdout). In this case, wav.scp contains shell commands only (to convert ogg into wav) and some of them happen to be incorrect shell commands because of these special characters.

**Comment by bmilde** [comment]
@akreal Thanks for the example!

I vaguely remember that we did move at some point to generate the files completely in the java exporter from http://nats.gitlab.io/swc/. In other words, we don't seem to use prepare_swc_german_wavscp.py anymore and we should probably delete it to avoid confusion. We also replaced all IDs with numbers, but since the problem is in the filename, we'd still encounter it with the current exported files.

@akoehn Can you check if we can include the escaping in the java code of SWC?

Another option is to patch the escaping in run.sh or we can also update the tar.gz that run.sh currently uses for the corpus.

**Comment by akoehn** [comment]
It has been a while; the relevant code is [here](https://bitbucket.org/natsuhh/swc/src/2685c599c249fb0569b7f8458f4695054fbb3f43/Aligner/src/main/java/swc/snippetextractor/KaldiSnippetExtractor.java?at=master&fileviewer=file-view-default#KaldiSnippetExtractor.java-109). Note that we only write "/path/to/articles/" as base path, that needs to be set to a sensible value anyway. @bmilde, did you replace that path manually?

I can push a fix for the java code tomorrow escaping the offending characters.

**Comment by akreal** [comment]
There is another problem you might want to fix while you are at it. Some multi-file recordings come in files with different number of channels or sampling rate. sox can not concatenate them and fails. There are 2 such cases in German and English parts: german/Ludwig_IV._(HRR) and english/Manchester. I ended up with the following command, that converts every file separately and then concatenates them:

```
sox "| sox -G data/wav/swc/german/Ludwig_IV._\(HRR\)/audio1.ogg -r 16k -t wav -c 1 -b 16 -e signed -" "| sox -G data/wav/swc/german/Ludwig_IV._\(HRR\)/audio2.ogg -r 16k -t wav -c 1 -b 16 -e signed -" "| sox -G data/wav/swc/german/Ludwig_IV._\(HRR\)/audio3.ogg -r 16k -t wav -c 1 -b 16 -e signed -" -t wav - |
```

**Pull request merged**
